name: fongmitv
on:
  schedule:
    - cron: '0 16 */2 * *' # 每2天 UTC 时间的 4:00 和 16:00 执行任务，对应的是中国时间的 12:00 和 24:00
  push:
    branches:
      - main
    paths: 
      - ".github/workflows/_fongmitv.yml"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:    
        include:
          - url: "https://github.com/FongMi/TV"
            name: FongMiTV
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3.4.0
  
      - name: Setup Java JDK
        uses: actions/setup-java@v3.10.0
        with:
          distribution: 'temurin'
          java-version: '8'
      
      - name: Clone project
        run: |
          git clone  "${{ matrix.url }}" project
          cd project
          git fetch origin
          git checkout release			
      - name: 获取时间
        run: | 
          cd project
          #lastcommit="$(TZ=UTC+8 git log -1 --pretty=format:%ci)"  #获取指定时区下的最新提交时间戳2023-03-29 19:14:27 +0800      
          ##leanback_lastcommit=$( git log -1 --format="%cd" --date=iso-strict release/) ##2023-03-29T19:14:27+08:00
          leanback_lastcommit=$( git log -1 --pretty=format:%ci  release/leanback-java.apk)  #获取指定时区下的最新提交时间戳2023-03-29 19:14:27 +0800
          echo " leanback-java.apk 的最新提交时间： $leanback_lastcommit"
          leanback_lastcommit=$(date --date="$leanback_lastcommit" +'%Y%m%d-%H%M')        
          echo "leanback_lastcommit 格式化时间: $leanback_lastcommit"
          
          #leanback_lastcommit=$(echo $leanback_lastcommit | cut -d'+' -f1 | xargs -I{} date -d {} +'%Y%m%d-%H%M')
          echo "leanback_lastcommit=$leanback_lastcommit" >> $GITHUB_ENV
          echo "leanback_lastcommit: $leanback_lastcommit 添加到环境变量"
          
          mobile_lastcommit=$( git log -1 --pretty=format:%ci  release/mobile-java.apk)
          mobile_lastcommit=$(date --date="$mobile_lastcommit" +'%Y%m%d-%H%M')
          echo "mobile_lastcommit=$mobile_lastcommit" >> $GITHUB_ENV
          echo "mobile_lastcommit: $mobile_lastcommit 添加到环境变量"
          TIMESTAMP=$(  date +'%Y%m%d-%H%M')
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
          echo "实时时间: $TIMESTAMP"
      - name: 更新版本名称
        if: ${{false}}
        run: |                                    
           sed -i "/versionName/s#[0-9a-zA-Z_\.\'\"-]\+\$#\'${{ matrix.name }}_${{env.lastcommit}}\'#" project/app/build.gradle
      - name: Build the app
        if: ${{false}}
        working-directory: ./project
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace      
    
      - name: 重命名，复制apk
        if: ${{true}}
        run: |
          mkdir -p ${{ github.workspace }}/upload/
          mv project/release/leanback-java.apk upload/leanback-java_${{env.leanback_lastcommit}}.apk
          mv project/release/leanback-python.apk upload/leanback-python_${{env.leanback_lastcommit}}.apk
          mv project/release/mobile-java.apk upload/mobile-java_${{env.mobile_lastcommit}}.apk
          mv project/release/mobile-python.apk upload/mobile-python_${{env.mobile_lastcommit}}.apk
      
      - name: kitkat 分支 
        run: | 
          cd project
          git fetch origin
          git checkout kitkat
          back_lastcommit=$( git log -1 --pretty=format:%ci  release/leanback.apk)  #获取指定时区下的最新提交时间戳2023-03-29 19:14:27 +0800
          echo "leanback.apk 的最新提交时间： $back_lastcommit"
          back_lastcommit=$(date --date="$back_lastcommit" +'%Y%m%d-%H%M')        
          echo "back_lastcommit 格式化时间: $back_lastcommit "
          
    
          echo "back_lastcommit=$back_lastcommit" >> $GITHUB_ENV
          echo "back_lastcommit: $back_lastcommit 添加到环境变量"
          cd ${{ github.workspace }}
          mv project/release/leanback.apk upload/leanback_$back_lastcommit.apk
          
          cd project
          git fetch origin
          git checkout release
      - name: 压缩文件
        run: |
          zip -r ${{ matrix.name }}_${{env.mobile_lastcommit}}.zip upload/
      - name: List APKs and zip
        run: |
          find ${{ github.workspace }} -type f -iname "*.apk"  
          find ${{ github.workspace }} -type f -iname "*.zip"
      - name: upload webdav_Koofr        
        uses: bxb100/action-upload-webdav@v1
        with:
           webdav_address: https://app.koofr.net/dav/Koofr/github/FonMiTV
           webdav_username: ${{secrets.WEBDAV_USERNAME}}
           webdav_password: ${{secrets.WEBDAV_PASSWORD}}
           webdav_upload_path: "/"
           files: "./upload/*.apk"
      - name: upload webdav_OneDrive       
        uses: bxb100/action-upload-webdav@v1
        with:
           webdav_address: https://app.koofr.net/dav/OneDrive/github/FonMiTV
           webdav_username: ${{secrets.WEBDAV_USERNAME}}
           webdav_password: ${{secrets.WEBDAV_PASSWORD}}
           webdav_upload_path: "/"
           files: "./upload/*.apk"
      - name: Upload APK
        if: ${{true}}
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ matrix.name }}_${{env.TIMESTAMP}}
          path: upload/*.apk
      
      - name: Release and Upload Assets
        if: ${{true}}    
        uses: ncipollo/release-action@v1
        with:
          name: ${{ matrix.name }}_${{env.mobile_lastcommit}}
          tag: ${{ matrix.name }}_${{env.mobile_lastcommit}}
          token: ${{ secrets.PAT }}
          allowUpdates: true
          removeArtifacts: true
          artifacts: |
            upload/*.apk
            *.zip
