name: release_test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
          
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - id: get-project
        name: Get project name
        run: echo "::set-output name=PROJECT::$(cat project-to-build)"
      - name: Clone project
        run: git clone --depth=1 ${{ steps.get-project.outputs.PROJECT }} project
        
      - name: 更新版本名称
        id: update_version_name
        run: |
          
          
          
           TIMESTAMP=$(date +'%Y%m%d%H%M%S')
           #echo "export VERSION_NAME=${TIMESTAMP}" >> $GITHUB_ENV
           echo '修改VersionName'
           sed -i "/versionName/s#[0-9a-zA-Z_\.\'\"-]\+\$#\'${TIMESTAMP}\'#" project/app/build.gradle
        #env:       
         #  VERSION_NAME: ${{ env.TIMESTAMP }} 
       
      - name: Build the app
        working-directory: ./project
        env:
          VERSION_NAME: "1.0.9"
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleRelease --stacktrace -PversionName="$VERSION_NAME"
      
      
      
      #使用 curl 命令从 GitHub 存储库的 Secrets 中下载 JKS 文件，并将其命名为 keystore.jks
      - name: Download keystore
        env:
           TOKEN: ${{ secrets.PAT }}
        run: |
           curl -sL -H "Authorization: token $TOKEN" -o keystore.jks ${{ secrets.KEYSTORE }}\
           #https://raw.githubusercontent.com/wenxin8/private/main/secret/my-release-key.jks  
      - name: 签名 APK
        run: |
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
            -keystore keystore.jks \
            -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
            -keypass ${{ secrets.KEY_PASSWORD }} project/app/build/outputs/apk/release/app-release-unsigned.apk release  #release是别名
          mv project/app/build/outputs/apk/release/app-release-unsigned.apk project/app/build/outputs/apk/release/app-release-signed.apk #改名
    
      
      
       
     #- name: Optimize APK
      # run: zipalign -v 4 project/app/build/outputs/apk/release/app-release-unsigned.apk project/app/build/outputs/apk/release/app-release.apk
          
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-build-apk
          path: ./**/*.apk
