name: release_test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
          
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - id: get-project
        name: Get project name
        run: echo "::set-output name=PROJECT::$(cat project-to-build)"
      - name: Clone project
        run: git clone --depth=1 ${{ steps.get-project.outputs.PROJECT }} project
      - name: Build the app
        working-directory: ./project
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleRelease --stacktrace
      

      
      #使用 curl 命令从 GitHub 存储库的 Secrets 中下载 JKS 文件，并将其命名为 keystore.jks
      - name: Download keystore
        env:
           TOKEN: ${{ secrets.PAT }}
        run: |
           curl -sL -H "Authorization: token $TOKEN" -o keystore.jks ${{ secrets.KEYSTORE }}\
           #https://raw.githubusercontent.com/wenxin8/private/main/secret/my-release-key.jks  
      - name: 签名 APK
        run: |
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
            -keystore keystore.jks \
            -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
            -keypass ${{ secrets.KEY_PASSWORD }} project/app/build/outputs/apk/release/app-release-unsigned.apk release  #release是别名
          mv project/app/build/outputs/apk/release/app-release-unsigned.apk project/app/build/outputs/apk/release/app-release-signed.apk #改名
       
      - name: Update Version Name
        id: update_version_name
        run: |
          apt-get update && apt-get install -y xmlstarlet
          xmlstarlet ed -L -N android="http://schemas.android.com/apk/res/android" 
          -u "/manifest/@android:versionName" 
          -v "${{ env.VERSION_NAME }}
          project/app/build/outputs/apk/release/app-release.apk
        env:
          VERSION_NAME: ${{ github.run_number }} 
       
      #- name: Optimize APK
      # run: zipalign -v 4 project/app/build/outputs/apk/release/app-release-unsigned.apk project/app/build/outputs/apk/release/app-release.apk
          
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-build-apk
          path: ./**/*.apk
