name: Debug_TVbox

on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      #  with:
      #   repository: owner/repo-name # 此处填写您要构建的 Github 仓库信息
      #   ref: main # 此处填写您要构建的 Github 仓库分支或 tag
      #   path: project # 在此处指定目标文件夹     
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      #- id: get-project
      # name: Get project name
      # run: echo "::set-output name=PROJECT::$(cat project-to-build)"
      - name: Clone project
        run: git clone --depth=1 "https://github.com/q215613905/TVBoxOS" project      
      - name: 更新版本名称
        id: update_version_name
        run: |          
           TIMESTAMP=$(date +'%Y%m%d')
           echo '修改VersionName'
           sed -i "/versionName/s#[0-9a-zA-Z_\.\'\"-]\+\$#\'q215613905_${TIMESTAMP}\'#" project/app/build.gradle
      - name: Build the app
        working-directory: ./project
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace      
         # apk_path=$(find ./project -iname "*.apk" -type f | sort -n | tail -1)  
      - name: 改名
        run: |
          TIMESTAMP2=$(date +'%Y%m%d%H')
          mv project/app/build/outputs/apk/debug/app-debug.apk project/app/build/outputs/apk/debug/q215613905_${TIMESTAMP2}.apk #改名
          export TIMESTAMP2
      - name: Create Directory
        run: mkdir -p ~/tvbox        
          cp project/app/build/outputs/apk/debug/*.apk ~/tvbox  #####${{ github.workspace }}##3
      - name: webdav        
        uses: bxb100/action-upload-webdav@v1
        with:
           webdav_address: https://app.koofr.net/dav/Koofr/github
           webdav_username: ${{secrets.WEBDAV_USERNAME}}
           webdav_password: ${{secrets.WEBDAV_PASSWORD}}
           webdav_upload_path: "/"
           files: "./project/app/build/outputs/apk/**/*.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk-${{ env.TIMESTAMP2 }}
          path: tvbox/*.apk
