name: release_TVbox
on:
  push:
    branches:
      - main
    paths: 
      - ".github/workflows/tvbox_release.yml"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3.4.0
      #  with:
      #   repository: owner/repo-name # 此处填写您要构建的 Github 仓库信息
      #   ref: main # 此处填写您要构建的 Github 仓库分支或 tag
      #   path: project # 在此处指定目标文件夹     
      - name: Setup Java JDK
        uses: actions/setup-java@v3.10.0
        with:
          distribution: 'temurin'
          java-version: '8'
      
      - name: Clone project
        run: git clone --depth=1 "https://github.com/q215613905/TVBoxOS" project
     
      - name: 获取时间
        run: | 
          cd project
          lastcommit="$(TZ=Asia/Shanghai git log -1 --pretty=format:%ci)"  #获取指定时区下的最新提交时间戳
          lastcommit=$(echo $lastcommit | sed 's/ [+-][0-9]\{4\}//g')  #时间戳字符串中的空格和加号后面的时区信息去掉
          lastcommit=$(date --date="$lastcommit" +'%Y%m%d-%H%M')  #将该时间戳格式化为 yyyymmdd-hhmm 的形式
          echo "lastcommit=$lastcommit" >> $GITHUB_ENV
          TIMESTAMP=$(TZ=Asia/Shanghai date +'%Y%m%d-%H%M')
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
      
      - name: 更新版本名称
        run: |                                    
           sed -i "/versionName/s#[0-9a-zA-Z_\.\'\"-]\+\$#\'q215613905_${{env.lastcommit}}\'#" project/app/build.gradle
      
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.2
      - name: Install Android Build-Tools and update environment variables
        run: |
          export ANDROID_HOME=/usr/local/android-sdk/
          export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/30.0.3/
          echo y | sdkmanager --install "build-tools;30.0.3"
      - name: Build the app
        working-directory: ./project
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleRelease --stacktrace      
         # apk_path=$(find ./project -iname "*.apk" -type f | sort -n | tail -1)  
      
     
      
      - name: Zipalign APK file
        run: $ANDROID_HOME/build-tools/30.0.3/zipalign -v 4 project/app/build/outputs/apk/release/app-release-unsigned.apk app-release.apk
      #- name: Zipalign APK file # 优化 APK 文件
      # run: zipalign -v 4 app/build/outputs/apk/release/app-release-unsigned.apk release/app-release.apk
      
      - name: Download keystore
        env:
           TOKEN: ${{ secrets.PAT }}
        run: |
           curl -sL -H "Authorization: token $TOKEN" -o keystore.jks ${{ secrets.KEYSTORE }}\
      
      - name: 签名 APK
        run: |
          mkdir -p ${{ github.workspace }}/releaseapk/
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
            -keystore keystore.jks \
            -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
            -keypass ${{ secrets.KEY_PASSWORD }} \
            -signedjar releaseapk/TVBox_q215613905_${{env.lastcommit}}.apk project/app/build/outputs/apk/release/app-release-unsigned.apk wx        
            
      
     # - name: 重命名apk
     #   run: |      
     #     mv project/app/build/outputs/apk/release/app-release.apk project/app/build/outputs/apk/release/TVBbox_q215613905_${TIMESTAMP}_release.apk  
          
      #- name: Create Directory and Copy APKs
       # run: |
          #mkdir -p ${{ github.workspace }}/releaseapk/        
         # cp project/app/build/outputs/apk/release/*.apk project/  #####${{ github.workspace }}##3
      - name: upload webdav        
        uses: bxb100/action-upload-webdav@v1
        with:
           webdav_address: https://app.koofr.net/dav/OneDrive/github
           webdav_username: ${{secrets.WEBDAV_USERNAME}}
           webdav_password: ${{secrets.WEBDAV_PASSWORD}}
           webdav_upload_path: "/"
           files: "./releaseapk/*.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v3.1.2
        with:
          name: TVBox_q215613905_${{env.lastcommit}}
          path: releaseapk/*.apk
